apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-powered-pdf-table-extractor-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-powered-pdf-table-extractor
  minReplicas: 1  # Keep at least 1 pod running (can set to 0 with special setup)
  maxReplicas: 5  # Scale up to 5 pods under heavy load
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Scale up when CPU > 70%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80  # Scale up when memory > 80%
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 minutes before scaling down
      policies:
      - type: Percent
        value: 50  # Scale down max 50% of pods at a time
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0  # Scale up immediately when needed
      policies:
      - type: Percent
        value: 100  # Can double pods quickly
        periodSeconds: 15
      - type: Pods
        value: 2  # Or add 2 pods at a time
        periodSeconds: 15
      selectPolicy: Max  # Use the more aggressive policy.

